import { Poppins } from "next/font/google";

import "./globals.css";

import { SessionProvider } from "next-auth/react";

import { Toaster } from "sonner";

import Navbar from "@/components/navbar.jsx";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} min-h-screen`}>
        <SessionProvider>
          <Navbar />
          {children}
          <Toaster
            position="top-center"
            closeButton
            richColors
            duration={2500}
          />
        </SessionProvider>
      </body>
    </html>
  );
}
